version: '3.1'

services:

  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: admin123

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin123
